#
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ jekyll serve --config _config.yml,_config_dev.yml

url: "http://localhost:4000"
urlimg: "http://localhost:4000/images/"
logo: "logo.png"

destination: _site

sass:
    sass_dir: _sass
    style: :expanded
    line_numbers: true

collections:
- faq
- faq_en
- media

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - design
    - _posts
    - blog
    - Drucksachen
    - pages/info.md
    - pages/design.md
    - build
    - assets/downloads
    - Guardfile
    - config.ru
    - .travis.yml

gems: ['jekyll-multiple-languages']
languages: ['de', 'en', 'fr']
language_default: 'de'
fill_default_content: true
